/*
 * generated by Xtext 2.17.0
 */
package jp.toppers.cfg.ide

import com.google.inject.Guice
import jp.toppers.cfg.CfgRuntimeModule
import jp.toppers.cfg.CfgStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CfgIdeSetup extends CfgStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CfgRuntimeModule, new CfgIdeModule))
	}
	
}
