/*
 * generated by Xtext 2.17.0
 */
package jp.toppers.cfg


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CfgStandaloneSetup extends CfgStandaloneSetupGenerated {

	def static void doSetup() {
		new CfgStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
