/*
 * generated by Xtext 2.17.0
 */
package jp.toppers.cfg.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class CfgWebModule extends AbstractCfgWebModule {
}
